source/AspNetGlobalizationAndLocalization/Entities/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Xaki;

namespace AspNetGlobalizationAndLocalization.Entities
{
    public class Book : ILocalizable
    {
        public int Id { get; set; }

        [Required(ErrorMessage = DataAnnotationMessages.Required), Localized]
        public string Name { get; set; }

        [Localized, DataType(DataType.Html)]
        public string Description { get; set; }
    }
}

source/AspNetGlobalizationAndLocalization/Entities/Culture.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetGlobalizationAndLocalization.Entities
{
    public class Culture
    {

        public int Id { get; set; }
        public string Name { get; set; }
        public virtual List<Resource> Resources { get; set; }
    }
}

source/AspNetGlobalizationAndLocalization/Entities/Resource.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetGlobalizationAndLocalization.Entities
{
    public class Resource
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public virtual Culture Culture { get; set; }
        public int CultureId { get; set; }  
    }
}

source/AspNetGlobalizationAndLocalization/Pages/BookEdit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetGlobalizationAndLocalization.Data;
using AspNetGlobalizationAndLocalization.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Xaki;

namespace AspNetGlobalizationAndLocalization.Pages
{
    public class BookEditModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IObjectLocalizer _objectLocalizer;

        public BookEditModel(ApplicationDbContext dbContext, IObjectLocalizer objectLocalizer)
        {
            _dbContext = dbContext;
            _objectLocalizer = objectLocalizer;
        }
      

        public Book Book { get; set; }
        public IActionResult OnGet(int bookId)
        {
            Book = _dbContext.Books.SingleOrDefault(i => i.Id == bookId);

            if (Book is null)
            {
                return NotFound();
            }
            return Page();

        }

        public IActionResult OnPost(Book book)
        {
            _dbContext.Entry(book).State = EntityState.Modified;

            _dbContext.SaveChanges();

            return RedirectToPage(nameof(Index));
        }
    }
}

source/AspNetGlobalizationAndLocalization/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AspNetGlobalizationAndLocalization.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

source/AspNetGlobalizationAndLocalization/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetGlobalizationAndLocalization.Data;
using AspNetGlobalizationAndLocalization.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Xaki;

namespace AspNetGlobalizationAndLocalization.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IObjectLocalizer _objectLocalizer;
        private readonly IHtmlLocalizer<IndexModel> _htmlLocalizer;

        public IndexModel(ApplicationDbContext dbContext, IObjectLocalizer objectLocalizer, IHtmlLocalizer<IndexModel> htmlLocalizer)
        {
            _dbContext = dbContext;
            _objectLocalizer = objectLocalizer;
            _htmlLocalizer = htmlLocalizer;
        }
        public List<Book> Books { get; set; }
        public void OnGet()
        {
            Books = _dbContext.Books.ToList();
            Books = _objectLocalizer.Localize<Book>(Books).ToList();
            ViewData["Message"] = _htmlLocalizer["Html Yerelleştirme : <b>Merhaba</b><i> {0}</i>", "Ayaz Duru"];
        }

        
        public IActionResult OnPostSetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

source/AspNetGlobalizationAndLocalization/Pages/BookEdit.cshtml
@page
@model AspNetGlobalizationAndLocalization.Pages.BookEditModel
@{
    ViewData["Title"] = "BookEdit";
}

<h1>BookEdit</h1>

<form method="post" asp-page="BookEdit">

    <input type="hidden" asp-for="Book.Id" />

    <div class="form-group">
        <label>@Localizer["Ad"]</label>
        <input localized-for="Book.Name" />
    </div>

    <div class="form-group">
        <label>@Localizer["Açıklama"]</label>
        <textarea localized-for="Book.Description"></textarea>
    </div>

    <button type="submit" class="btn btn-dark">@Localizer["Güncelle"]</button>
</form>

source/AspNetGlobalizationAndLocalization/Pages/Index.cshtml
@page

@model IndexModel
@inject EFStringLocalizerFactory efStringLocalizerFactory
@{
    ViewData["Title"] = "Home page";
    var efStringLocalizer = efStringLocalizerFactory.Create(null);
}

<div class="text-center">
    <h1 class="display-4">@Localizer["Hoşgeldiniz"] @System.Threading.Thread.CurrentThread.CurrentUICulture.Name</h1>
    <p>@efStringLocalizer["Veritabanından Merhaba"]</p>
  @ViewData["Message"]
    <table class="table table-hover">
        <thead>
        <tr>
            <th>@Localizer["Ad"]</th>
            <th>@Localizer["Açıklama"]</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var book in Model.Books)
        {
            <tr>
                <td>@book.Name</td>
                <td>@Html.Raw(book.Description)</td>
                <td style="width: 1%;"><a asp-page="BookEdit" asp-route-bookId="@book.Id">@Localizer["Düzenle"]</a></td>
            </tr>
        }
        </tbody>
    </table>
</div>

source/AspNetGlobalizationAndLocalization/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetGlobalizationAndLocalization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AspNetGlobalizationAndLocalization</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">@Localizer["Ana Sayfa"]</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; @System.DateTime.Now.Year</p>
                </div>
                <div class="col-md-6 text-right">
                   <partial name="_SelectLanguagePartial"/>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

source/AspNetGlobalizationAndLocalization/Pages/Shared/_SelectLanguagePartial.cshtml
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName, Selected = (c.Equals(System.Threading.Thread.CurrentThread.CurrentUICulture)) })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-page="Index" asp-page-handler="SetLanguage" asp-route-returnUrl="@returnUrl" 
          method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Dil:"]</label> <select name="culture"
                                                                                                               onchange="this.form.submit();"
                                                                                                               asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>